//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonataCinemaV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int ID_Blog { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public int ID_NhanVien { get; set; }
        public string TheLoai { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<int> LuotXem { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
