//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonataCinemaV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMessage
    {
        public int ID_Chat { get; set; }
        public string RoomId { get; set; }
        public Nullable<int> ID_KhachHang { get; set; }
        public Nullable<int> ID_NhanVien { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string Role { get; set; }
        public string Status { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
