//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonataCinemaV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComboOrder
    {
        public int ID_ComboOrder { get; set; }
        public int ID_ThanhToan { get; set; }
        public int ID_Combo { get; set; }
        public int SoLuong { get; set; }
        public decimal GiaTien { get; set; }
    
        public virtual Combo Combo { get; set; }
        public virtual ThanhToan ThanhToan { get; set; }
    }
}
