//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonataCinemaV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGia
    {
        public int ID_DanhGia { get; set; }
        public int ID_KhachHang { get; set; }
        public int ID_Phim { get; set; }
        public Nullable<double> DiemDanhGia { get; set; }
        public Nullable<System.DateTime> ThoiGianDanhGia { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual Phim Phim { get; set; }
    }
}
