//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonataCinemaV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemThuong
    {
        public int ID_KhachHang { get; set; }
        public Nullable<int> DiemHienCo { get; set; }
        public Nullable<int> DiemDaDoi { get; set; }
        public Nullable<int> TongDiemTichLuy { get; set; }
        public Nullable<System.DateTime> CapNhatLanCuoi { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
