//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonataCinemaV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ghe
    {
        public int ID_Ghe { get; set; }
        public int ID_Phong { get; set; }
        public string TenGhe { get; set; }
        public string TrangThai { get; set; }
    
        public virtual PhongChieu PhongChieu { get; set; }
    }
}
