//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonataCinemaV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ghe_TrangThai
    {
        public int ID_TrangThai { get; set; }
        public int ID_LichChieu { get; set; }
        public int ID_Ghe { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> ThoiGianGiu { get; set; }
    
        public virtual Ghe Ghe { get; set; }
        public virtual LichChieu LichChieu { get; set; }
    }
}
