//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonataCinemaV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichChieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LichChieu()
        {
            this.Ves = new HashSet<Ve>();
        }
    
        public int ID_LichChieu { get; set; }
        public int ID_Phim { get; set; }
        public int ID_Phong { get; set; }
        public System.TimeSpan GioChieu { get; set; }
        public System.DateTime NgayChieu { get; set; }
    
        public virtual Phim Phim { get; set; }
        public virtual PhongChieu PhongChieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ve> Ves { get; set; }
    }
}
