//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonataCinemaV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phim()
        {
            this.LichChieux = new HashSet<LichChieu>();
            this.DanhGias = new HashSet<DanhGia>();
        }
    
        public int ID_Phim { get; set; }
        public string TenPhim { get; set; }
        public List<Phim> RandomMovie { get; set; } = new List<Phim>();
        public string TheLoai { get; set; }
        public Nullable<int> ThoiLuong { get; set; }
        public Nullable<double> DanhGia { get; set; }
        public Nullable<byte> NoiBat { get; set; }
        public string TrangThai { get; set; }
        public string MoTa { get; set; }
        public string Poster { get; set; }
        public string Banner { get; set; }
        public string Trailer { get; set; }
        public string DienVien { get; set; }
        public string DaoDien { get; set; }
        public string NhaSanSuat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichChieu> LichChieux { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
    }
}
