//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonataCinemaV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ve
    {
        public int ID_Ve { get; set; }
        public int ID_ThanhToan { get; set; }
        public int ID_KhachHang { get; set; }
        public int ID_LichChieu { get; set; }
        public string ChoNgoi { get; set; }
        public decimal Gia { get; set; }
        public Nullable<int> DiemThuong { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public string TrangThaiGhe { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual LichChieu LichChieu { get; set; }
        public virtual ThanhToan ThanhToan { get; set; }
    }
}
